version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: app
      MYSQL_PASSWORD: AkNt-M?{Y;jq3[2W4)ey<S
      MYSQL_ROOT_PASSWORD: AkNt-M?{Y;jq3[2W4)ey<S
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
